package bundle

import (
	"crypto/ed25519"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"testing"
)

func makeEnvelope(t *testing.T, manifest any) (*Envelope, ed25519.PublicKey) {
	t.Helper()
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	canon, err := CanonicalJSON(manifest)
	if err != nil {
		t.Fatal(err)
	}
	sig := ed25519.Sign(priv, canon)
	sum := sha256.Sum256(canon)
	raw, err := json.Marshal(manifest)
	if err != nil {
		t.Fatal(err)
	}
	return &Envelope{
		BundleSeq:    1,
		Manifest:     raw,
		ManifestHash: "sha256:" + hex.EncodeToString(sum[:]),
		SignatureB64: base64.StdEncoding.EncodeToString(sig),
		SigningKeyID: "test-key",
	}, pub
}

func TestVerify_HappyPath(t *testing.T) {
	m := map[string]any{
		"tenant": "acme", "environment": "prod", "bundle_seq": 1,
		"created_at": "2026-07-16T00:00:00Z", "max_age_hours": 72,
		"policies": []any{}, "detectors": []any{},
	}
	env, pub := makeEnvelope(t, m)
	trust := &StaticTrustStore{Keys: map[string]ed25519.PublicKey{"test-key": pub}}
	if _, err := Verify(env, trust); err != nil {
		t.Fatalf("expected verify, got %v", err)
	}
}

func TestVerify_RejectsWrongKey(t *testing.T) {
	m := map[string]any{
		"tenant": "acme", "environment": "prod", "bundle_seq": 1,
		"created_at": "2026-07-16T00:00:00Z", "max_age_hours": 72,
		"policies": []any{}, "detectors": []any{},
	}
	env, _ := makeEnvelope(t, m)
	other, _, _ := ed25519.GenerateKey(rand.Reader)
	trust := &StaticTrustStore{Keys: map[string]ed25519.PublicKey{"test-key": other}}
	if _, err := Verify(env, trust); err == nil {
		t.Fatal("expected signature verification failure")
	}
}

func TestVerify_RejectsTamperedManifest(t *testing.T) {
	m := map[string]any{
		"tenant": "acme", "environment": "prod", "bundle_seq": 1,
		"created_at": "2026-07-16T00:00:00Z", "max_age_hours": 72,
		"policies": []any{}, "detectors": []any{},
	}
	env, pub := makeEnvelope(t, m)
	trust := &StaticTrustStore{Keys: map[string]ed25519.PublicKey{"test-key": pub}}
	// Tamper: bump bundle_seq in the manifest after signing.
	env.Manifest = []byte(`{"tenant":"acme","environment":"prod","bundle_seq":2,"created_at":"2026-07-16T00:00:00Z","max_age_hours":72,"policies":[],"detectors":[]}`)
	if _, err := Verify(env, trust); err == nil {
		t.Fatal("expected tamper detection")
	}
}

func TestVerify_RejectsUnknownKeyID(t *testing.T) {
	m := map[string]any{"tenant": "acme"}
	env, _ := makeEnvelope(t, m)
	trust := &StaticTrustStore{Keys: map[string]ed25519.PublicKey{}}
	if _, err := Verify(env, trust); err == nil {
		t.Fatal("expected untrusted-key rejection")
	}
}

// TestCanonicalJSON_CrossLanguageHash pins the Go canonicaliser against a
// known good Python canonicaliser output. If this drifts, the Control API
// and gateway will disagree on manifest_hash and every bundle-verify fails.
// Baseline generated by control/guardx_control/signing/canonical.py on the
// same input document (see harness/canonical_parity_test.py).
func TestCanonicalJSON_CrossLanguageHash(t *testing.T) {
	src := `{"tenant":"acme","environment":"prod","bundle_seq":42,"created_at":"2026-07-16T00:00:00Z","max_age_hours":72,"policies":[],"detectors":[]}`
	var v any
	if err := json.Unmarshal([]byte(src), &v); err != nil {
		t.Fatal(err)
	}
	b, err := CanonicalJSON(v)
	if err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(b)
	got := hex.EncodeToString(sum[:])
	const want = "3decd8e0c4e7092106104b1385915f0f0b2759dc86b38fa00f9b911e46667560"
	if got != want {
		t.Fatalf("canonical hash mismatch:\n  got:  %s\n  want: %s\n  bytes: %s", got, want, b)
	}
}

func TestCanonicalJSON_KeyOrderStable(t *testing.T) {
	a := map[string]any{"b": 1, "a": 2}
	b := map[string]any{"a": 2, "b": 1}
	ca, _ := CanonicalJSON(a)
	cb, _ := CanonicalJSON(b)
	if string(ca) != string(cb) {
		t.Fatalf("canonical outputs diverge: %s vs %s", ca, cb)
	}
	if string(ca) != `{"a":2,"b":1}` {
		t.Fatalf("unexpected canonical form: %s", ca)
	}
}
